# Data Preprocessing

## Importing the libraries

In [19]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

## Importing Dataset

In [20]:
data_set = pd.read_excel('Covid_Data_new.xlsx')
x= data_set.iloc[:, :-1].values
y=data_set.iloc[:, -1].values

In [21]:
print(x)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [22]:
print(y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']





## Handling Missing Data

In [23]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 0:5:4])
x[:, 0:5:4] = imputer.transform(x[:, 0:5:4])
print(x)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

## Encoding Categorical Data

### Encoding independent variables

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,5,6])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 12.0 97.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 15.0 94.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 10.0 97.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 13.0 94.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 12.0 97.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 13.0 93.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 15.0 92.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 18.0 66.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 19.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 20.0 93.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 17.0 93.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 16.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 18.0 93.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 20.0 92.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 25.0 93.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 24.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 1.0 0.0 26.0 94.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 28.0 99.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 29.0 93.0]
 [0.0 1.0 1.0 0.0 1.

### Encoding dependent variables

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


## Splitting data into Test set & Training Set


In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=42)


In [38]:
print(x_train)


[[1.0 0.0 1.0 0.0 86.0 'yes' 'yes' 71.0]
 [0.0 1.0 0.0 0.0 35.0 'no' 'yes' 92.0]
 [1.0 0.0 1.0 0.0 75.0 'no' 'yes' 72.0]
 [1.0 0.0 1.0 0.0 42.0 'no' 'no' 92.0]
 [1.0 0.0 1.0 0.0 74.0 'yes' 'yes' 75.0]
 [1.0 0.0 1.0 0.0 62.0 'yes' 'yes' 68.0]
 [0.0 1.0 0.0 0.0 24.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 0.0 48.0 'no' 'yes' 93.0]
 [1.0 0.0 1.0 0.0 58.0 'no' 'no' 70.0]
 [0.0 1.0 0.0 0.0 45.130434782608695 'yes' 'no' 90.0]
 [0.0 1.0 0.0 0.0 15.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 1.0 70.0 'no' 'yes' 88.0]
 [1.0 0.0 1.0 0.0 52.0 'yes' 'yes' 80.0]
 [1.0 0.0 1.0 0.0 60.0 'yes' 'yes' 68.0]
 [1.0 0.0 1.0 0.0 54.0 'yes' 'yes' 70.0]
 [1.0 0.0 0.0 1.0 29.0 'no' 'no' 93.0]
 [1.0 0.0 1.0 0.0 78.0 'yes' 'yes' 71.0]
 [1.0 0.0 1.0 0.0 36.0 'yes' 'no' 90.0]
 [0.0 1.0 0.0 0.0 30.0 'yes' 'no' 86.0]
 [1.0 0.0 1.0 0.0 50.0 'yes' 'yes' 77.0]
 [1.0 0.0 0.0 1.0 18.0 'no' 'no' 93.0]
 [1.0 0.0 1.0 0.0 69.0 'no' 'yes' 53.0]
 [1.0 0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [1.0 0.0 1.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 1.0 0.0 0.0 18.0 'no

In [29]:
print(x_test)

[[1.0 0.0 1.0 0.0 86.0 'no' 'yes' 76.0]
 [0.0 1.0 0.0 0.0 35.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 0.0 61.0 'no' 'yes' 90.0]
 [1.0 0.0 1.0 0.0 59.0 'yes' 'no' 68.0]
 [0.0 1.0 0.0 0.0 32.0 'no' 'yes' 84.0]
 [1.0 0.0 1.0 0.0 80.0 'no' 'yes' 92.0]
 [1.0 0.0 1.0 0.0 68.0 'yes' 'no' 67.0]
 [1.0 0.0 1.0 0.0 40.0 'no' 'no' 92.0]
 [1.0 0.0 1.0 0.0 63.0 'yes' 'yes' 66.0]
 [1.0 0.0 1.0 0.0 38.0 'no' 'no' 75.0]
 [1.0 0.0 0.0 1.0 15.0 'no' 'no' 94.0]
 [1.0 0.0 1.0 0.0 36.0 'yes' 'no' 90.0]
 [1.0 0.0 0.0 1.0 70.0 'no' 'yes' 88.0]
 [1.0 0.0 1.0 0.0 42.0 'no' 'no' 92.0]]


In [30]:
print(y_train)

[1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0
 1 0 1 0 1 1 1 0 0 1 0 1 0 0 1 0 0 0 1]


In [31]:
print(y_test)

[1 0 0 1 0 0 1 0 1 1 0 0 0 0]


## Feature Scaling

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 6:] = sc.fit_transform(x_train[:, 6:])
x_test[:, 6:] = sc.transform(x_test[:, 6:])

In [42]:
print(x_train)

[[1.0 0.0 0.0 1.0 0.0 1.0 0.632455532033676 0.9649012813540154
  -0.4944132324730441 1.6605950326521113 -0.9941858494300264]
 [0.0 1.0 1.0 0.0 0.0 1.0 -1.5811388300841902 -1.0363754503432019
  -0.4944132324730441 -0.5372483818439074 0.957435414508189]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.632455532033676 0.9649012813540154
  -0.4944132324730441 1.1865503746235584 -0.9012515035282067]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.632455532033676 0.9649012813540154
  -0.4944132324730441 -0.23558359946210097 0.957435414508189]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.632455532033676 0.9649012813540154
  -0.4944132324730441 1.1434554057118715 -0.6224484658227473]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.632455532033676 0.9649012813540154
  -0.4944132324730441 0.6263157787716319 -1.2729888871354857]
 [0.0 1.0 1.0 0.0 1.0 0.0 -1.5811388300841902 -1.0363754503432019
  -0.4944132324730441 -1.0112930398724607 0.957435414508189]
 [0.0 1.0 1.0 0.0 0.0 1.0 -1.5811388300841902 -1.0363754503432019
  -0.4944132324730441 0.022986214008018896 1.0503697604

In [43]:
print(x_test)

[[1.0 0.0 1.0 0.0 0.0 1.0 0.632455532033676 -1.0363754503432019
  2.022599587389726 -0.9681980709607739 0.3998293390972703]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.632455532033676 -1.0363754503432019
  2.022599587389726 -1.6146226046360737 1.4221071440172879]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.632455532033676 0.9649012813540154
  -0.4944132324730441 0.8848855922417518 -1.3659232330373057]
 [0.0 1.0 1.0 0.0 1.0 0.0 -1.5811388300841902 -1.0363754503432019
  -0.4944132324730441 -1.4853376979010136 1.1433041063118285]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.632455532033676 0.9649012813540154
  -0.4944132324730441 0.497030872036572 -1.2729888871354857]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.632455532033676 -1.0363754503432019
  2.022599587389726 -0.838913164225714 1.6079758358209275]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.632455532033676 -1.0363754503432019
  2.022599587389726 -1.1836729155192072 1.0503697604100088]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.632455532033676 0.9649012813540154
  -0.4944132324730441 -0.0632037238153544 0.8645010686063692]
 [1